### ISSUE TITLE
cant scroll in thepasswort Manager

### ISSUE THREAD

**Issue by Andimanjac** [Metalit/PlaylistManager#14]
I cant scroll in the password Manager!

**Comment by Metalit** [comment]
Not sure what you mean by this, there is no password manager

**Comment by Andimanjac** [comment]
Sorry, I mean when I’m in the Playlist Manager, I can’t scroll down. Am 16.09.2024 um 18:47 schrieb Metalit ***@***.***>:﻿
Not sure what you mean by this, there is no password manager

**Comment by Metalit** [comment]
Do you mean with the buttons on the scrollbar, or with the controller joystick? Are you sure there are enough songs for scrolling?

**Comment by Andimanjac** [comment]
The Problem is only in the Playlist manager (songlist editor). When I’m not in the playlist manager, I can scroll the playlist with the bottons on the scrollbar and with the stick. But when I’m in the songlist/playlist manager I can’t scroll with the stick and there are any scrollbottons. Yes I’m sure that there are enough songlist (not any songs) , because I can see the edge of the follow songlist below But I can’t go down ! I uninstalled the mod for the songlist editor beatsaber, I and I even uninstalled bestsaber. But I ther is still the same problem. Thank you for help!Am 17.09.2024 um 19:03 schrieb Metalit ***@***.***>:﻿
Do you mean with the buttons on the scrollbar, or with the controller joystick? Are you sure there are enough songs for scrolling?
