### ISSUE TITLE
Song covers not showing up immediately

### ISSUE THREAD

**Issue by L3Home** [Metalit/PlaylistManager#9]
I've noticed that when I save a new song cover, it is not immediately available for use on a playlist created immediately or shortly after it is saved.

I'm not certain what triggers it to be available in the list of covers, whether it's the song list updating, leaving Beat Saber and re-entering the game, or some other event, but it does seem to require some additional action after saving, before it shows up in the covers list.

**Comment by Metalit** [comment]
Fixed with the 1.37 rework
